version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: pratyaksha_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: pratyaksha_core
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pratyaksha_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pratyaksha@suryasanc.in
      PGADMIN_DEFAULT_PASSWORD: Pratyaksha@321
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
